#!/usr/bin/env python
"""Generate public/rss.xml from the log pages themselves.

Derives every item from src/pages/log/*.astro -- canonical URL, title,
description and the human date in the page's own <div class="meta"> line -- so
there is no second list to keep in sync. Publish a new post and re-run this;
the feed follows automatically.

RSS is the site's only zero-friction follow mechanism: no email, no personal
data, no processor, so nothing here touches the DSGVO surface.

Usage:  python scripts/generate_rss.py [--check]
"""
import glob
import io
import os
import re
import sys
from datetime import datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE = 'https://hoppingproject.netlify.app'
OUT = os.path.join(ROOT, 'public', 'rss.xml')

TITLE = 'bench.log'
DESC = ('A running log of local AI work on ordinary hardware: RTX 5070 Ti '
        'benchmarks, ComfyUI and Flux LoRA workflows, on-prem RAG '
        'deployments. Real configs and measured numbers, written as the '
        'work happens.')

MONTHS = {m: i + 1 for i, m in enumerate(
    ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
     'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])}


def esc(t):
    return (t.replace('&', '&amp;').replace('<', '&lt;')
             .replace('>', '&gt;').replace('"', '&quot;'))


def grab(pattern, text, default=''):
    m = re.search(pattern, text, re.S)
    return m.group(1).strip() if m else default


def collect():
    posts = []
    for path in glob.glob(os.path.join(ROOT, 'src', 'pages', 'log', '*.astro')):
        s = io.open(path, encoding='utf-8').read()
        canon = grab(r'<link rel="canonical" href="([^"]+)">', s)
        if not canon:
            continue
        title = (grab(r'<meta property="og:title" content="([^"]+)">', s)
                 or grab(r'<title>(.*?) \u2014 Bench Log</title>', s))
        desc = (grab(r'<meta property="og:description" content="([^"]+)">', s)
                or grab(r'<meta name="description" content="([^"]+)">', s))
        meta = grab(r'<div class="meta">(.*?)</div>', s)
        dm = re.match(r'(\d{1,2})\s+([A-Z][a-z]{2})\s+(\d{4})', meta)
        if not dm:
            print('WARNING: no parsable date in %s, skipped' % os.path.basename(path))
            continue
        dt = datetime(int(dm.group(3)), MONTHS[dm.group(2)], int(dm.group(1)), 10, 0, 0)
        slug = canon.rstrip('/').split('/log/')[-1]
        posts.append((dt, title, desc, canon, slug))
    posts.sort(reverse=True)
    return posts


def build(posts):
    now = datetime.utcnow().strftime('%a, %d %b %Y %H:%M:%S +0000')
    items = []
    for dt, title, desc, canon, slug in posts:
        items.append(
            '  <item>\n'
            '    <title>%s</title>\n'
            '    <link>%s</link>\n'
            '    <guid isPermaLink="true">%s</guid>\n'
            '    <description>%s</description>\n'
            '    <pubDate>%s</pubDate>\n'
            '    <enclosure url="%s/og/%s.png" type="image/png" length="0"/>\n'
            '  </item>' % (esc(title), canon, canon, esc(desc),
                           dt.strftime('%a, %d %b %Y %H:%M:%S +0200'),
                           BASE, slug))
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<!--\n'
        '  Generated by scripts/generate_rss.py from src/pages/log/*.astro.\n'
        '  Do not hand-edit: re-run the script after publishing a post.\n'
        '-->\n'
        '<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">\n'
        '<channel>\n'
        '  <title>%s</title>\n'
        '  <link>%s/</link>\n'
        '  <description>%s</description>\n'
        '  <language>en</language>\n'
        '  <lastBuildDate>%s</lastBuildDate>\n'
        '  <atom:link href="%s/rss.xml" rel="self" type="application/rss+xml"/>\n'
        '%s\n'
        '</channel>\n'
        '</rss>\n' % (esc(TITLE), BASE, esc(DESC), now, BASE, '\n'.join(items)))


def main():
    posts = collect()
    xml = build(posts)
    if '--check' in sys.argv:
        cur = io.open(OUT, encoding='utf-8').read() if os.path.exists(OUT) else ''
        strip = lambda t: re.sub(r'<lastBuildDate>.*?</lastBuildDate>', '', t)
        if strip(cur) != strip(xml):
            print('rss.xml is STALE - run: python scripts/generate_rss.py')
            return 1
        print('rss.xml current (%d items)' % len(posts))
        return 0
    io.open(OUT, 'w', encoding='utf-8', newline='').write(xml)
    print('wrote %s with %d items:' % (os.path.relpath(OUT, ROOT), len(posts)))
    for dt, title, _, _, _ in posts:
        print('  %s  %s' % (dt.strftime('%Y-%m-%d'), title[:64]))
    return 0


if __name__ == '__main__':
    sys.exit(main())
